backend/account/serializers.py
backend/account/urls.py
backend/account/views.py
backend/config/exceptions.py
backend/config/settings/base.py
backend/config/utils.py

> #7 
> 로그인 기능 구현
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FEAT] 로그인 기능 구현

---

backend/account/serializers.py
backend/account/views.py
backend/config/exceptions.py

> #10
> - 토큰 발급 부분에 예외처리 추가
> - 시리얼라이저에 필수 항목 필드 추가
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[REFACTOR] 회원가입 기능 리펙토링

---

backend/account/serializers.py
backend/account/views.py
backend/config/exceptions.py
backend/config/utils.py

[FIX] 예외 처리 수정 #17

---

backend/config/exceptions.py
backend/config/settings/base.py
backend/config/utils.py

> #22 
> 인증 관련 커스텀 예외 발생 삭제
> simplejwt 예외 발생 시, 해당 포맷을 커스텀하여 응답하도록 수정
> LANGUAGE_CODE 변경
> 사용 하지 않는 커스텀 예외 삭제

[FIX] 커스텀 예외 처리 핸들러 수정 #22

---

backend/attendance/views.py

[FEAT] 출석 현황 조회 구현 #31

---

backend/attendance/serializers.py
backend/attendance/views.py

> #33
> views.py에 details 메서드 구현
> AttendanceDetailSerializer 구현

[FEAT] 출석 내역 조회 구현 #33

---

backend/config/settings/base.py
backend/config/settings/dev.py

> #35
> USE_TZ 설정 True로 변경
> 데이터베이스 설정 옵션에 timezone=Asia/Seoul 설정 추가

[CHORE] 시간 관련 설정 변경 #35

---

backend/account/models.py
backend/account/views.py
backend/attendance/models.py

> #41
> 회원가입, 로그인 성공 응답 메세지 필드명 변경
> accout 모델 필드 타입 수정
> attendance 모델 필드 타입 수정

[STYLE] 필드 타입 수정 #41

---

backend/account/serializers.py
backend/account/urls.py
backend/account/views.py

> #43 
> 인증 번호 및 이메일 검증 시리얼라이저 구현
> 인증 번호 확인 및 처리 로직 구현

[FEAT] 인증 번호 확인 기능 구현 #43

---

backend/account/serializers.py

> #47
> 인증 번호 요청 시 이미 인증 완료된 사용자인지 검증하는 로직 추가

[REFACTOR] 인증 번호 요청 기능 수정

---

backend/account/serializers.py
backend/account/urls.py
backend/account/views.py

> #49
> 토큰 재발급 기능 구현
> TokenRefreshSerializer을 상속하여 커스텀 시리얼라이저 구현하여 값 검증

[FEAT] 토큰 재발급 기능 구현 #49

---

backend/account/serializers.py
backend/account/urls.py
backend/account/views.py
backend/config/exceptions.py
backend/config/settings/base.py

> #51 
> token_blacklist 설정 추가
> LogoutSerializer 구현
> 로그아웃 로직 구현

[FEAT] 로그아웃 기능 구현 #51

---

backend/account/serializers.py
backend/account/urls.py
backend/account/views.py

> #53
> UserPasswordUpdateAPIView 구현
> PasswordUpdateSerializer 구현하여 유효성 검증 및 저장 로직 구현

[FEAT] 비밀번호 변경 기능 구현

---

.gitignore
backend/config/settings/base.py

> #62
> base.py에 로거 설정
> .gitignore에 logs 디렉토리 추가

[CHORE] 로거 설정 #62

---

backend/ranking/views.py

> None
> 개발 시 삽입 되었던 불필요한 print문을 제거하였습니다.

[REFACTOR] 불필요 print문 제거

---

.github/workflows/deploy.yml
backend/config/settings/dev.py
backend/config/settings/prod.py
backend/init.sh
backend/requirements.txt
deploy.sh
docker-compose.prod.yml

> #69 
> 운영 환경용 설정 파일 작성
> 운영 환경에 맞춰 스크립트 변경
> 운영 환경용 docker-compose 작성

[CHORE] 운영 환경 설정 #69

---

.github/workflows/deploy.yml
backend/account/views.py

> #81
> Github Actions 스크립트에 Redis URI 추가
> 회원가입 인증 로직 내 순서 변경

[FIX] 운영 환경 Redis 연결 문제 해결 #81

---

.github/workflows/deploy.yml
backend/account/tasks.py
backend/account/views.py
backend/config/celery.py
backend/config/settings/dev.py
backend/config/settings/prod.py
backend/init.sh
backend/requirements.txt

> #86 
> 이메일 전송 기능 비동기 방식으로 수정

[REFACTOR] 이메일 전송 기능 비동기 방식으로 수정 #86

---

.github/workflows/deploy.yml

> #88 
> Github Actions 워크플로에 실행 조건 추가

[FIX] 개인 레포지토리에서 Github Actions 워크플로 실행되지 않게 수정

---

backend/config/exceptions.py
backend/config/settings/base.py
backend/config/urls.py
backend/mypage/admin.py
backend/mypage/apps.py
backend/mypage/models.py
backend/mypage/serializers.py
backend/mypage/tests.py
backend/mypage/urls.py
backend/mypage/views.py

> #98 
>  마이페이지 앱 생성 및 설정
> 마이페이지 조회 구현
> 마이페이지 수정 구현

[FEAT] 마이페이지 구현 #98

---

docker-compose.prod.yml
docker-compose.yml

> #103
> backend 컨테이너 시간 설정
> nginx 컨테이너 외부 포트 수정

[CHORE] docker-compose 설정 수정 #103

---

backend/ranking/serializers.py
backend/ranking/views.py

[FIX] Response 포멧 수정

---

backend/mypage/serializers.py

> #106
> 마이페이지 운동 난이도 필드 타입 변경

[FIX] 마이페이지 운동 난이도 필드 타입 변경 #106

---

deploy.sh
nginx/Dockerfile
nginx/nginx

> #74 
> logrotate 설정 변경
> 배포 스크립트에 logrotate 설정 파일을 호스트에 복사하는 명령어 추가
> Dockerfile에서 logrotate 관련 내용 삭제

[FIX] logrotate 실행되지 않는 문제 해결 #74

---

backend/record/views.py

> #112 
> 운동 기록 list 응답 반환 시에 요청한 user의 데이터만 반환하도록 필터링

[FIX] 운동 기록 모든 유저의 데이터 반환되는 문제 해결

---

backend/config/settings/prod.py

> #109 
> CORS_ORIGIN_WHITELIST 제거 후 CORS_ALLOWED_ORIGINS 추가
> CORS_ALLOWED_ORIGINS에 도메인 추가

[FIX] Invalid HTTP_HOST header 에러 수정 #109

---

backend/account/views.py

> #110 
> 회원가입 시 토큰 발급하는 부분 삭제

[REFACTOR] 회원가입 후 토큰 발급 안 하게 변경 #110

---

backend/record/serializers.py

> #111
> 운동 종료 이전에 기록하지 못하게 변경
> 동일한 날짜에 한 번만 기록할 수 있게 변경

[FIX] 운동 기록 생성 시 검증 로직 추가 #111

---

backend/ranking/management/commands/runapscheduler.py

> #121
> 랭킹 집계 스케쥴러 명령어에 day, hour, minute 인자 추가
close #121

[FEAT] 랭킹 집계 스케쥴러 명령어 파라미터 추가

---

backend/init.sh
backend/record/serializers.py

> #120
> 기록이 없는 날짜에 기록이 되지 않는 에러 해결
> 스케줄러 실행 명령어 수정

[FIX] 기록이 없는 날짜에 기록이 되지 않는 에러 #120

---

backend/ranking/jobs.py
backend/ranking/management/commands/runapscheduler.py

[FIX] 랭킹 집계 기간 2주로 변경 

---

.github/workflows/deploy.yml
backend/config/settings/prod.py

> #128 
> 환경 변수 파일에서 불러오는 방식으로 변경
> Github Actions 스크립트에 추가

[CHORE] CORS 설정 변경 #128

---

backend/account/serializers.py

> #127 
> 회원가입 시 비밀번호 대소문자 구분하지 않도록 변경

[REFACTOR] 비밀번호 요구사항 간소화 #127

---

backend/config/settings/prod.py
deploy.sh
docker-compose.prod.yml
nginx/Dockerfile
nginx/nginx-app.conf

> #71 
> Django 설정 파일 수정
> Nginx 설정 파일 수정
> Nginx Docker 파일 수정
> 운영용 도커 컴포즈 파일 수정
> 배포 스크립트 수정

[CHORE] 도메인에 HTTPS 적용 #71

---

.github/workflows/deploy.yml

> #129 
> Github Actions 워크플로에 CSRF_TRUSTED_ORIGINS 변수 추가

[CHORE] CSRF 설정 추가 #129

---

backend/config/settings/prod.py
backend/init.sh
docker-compose.prod.yml

> #134
> Celery 다운 시 재실행을 위해 별도의 컨테이너 구성
> setting에 CELERY_BROKER_TRANSPORT_OPTIONS 설정 추가

[FIX] Celery 다운되는 문제 해결 #134

---

.github/workflows/deploy.yml
backend/config/settings/prod.py
backend/init.sh

> #136
> 설정 파일에서 CELERY_RESULT_BACKEND를 redis 컨테이너에서 RDS로 수정
> init.sh에 Celery 관련 테이블 생성 명령어 추가
> Github Actions 워크플로에서 CELERY_RESULT_BACKEND 설정 제거

[CHORE] Celery 실행 결과 저장 위치 변경 #136

---

backend/account/serializers.py

> #138
> 시리얼라이저에 가입은 됐지만 승인이 안된 사용자 검증 로직 추가

[FEAT] 가입은 됐지만 승인이 안된 사용자 검증 로직 추가 #138

---

backend/requirements.txt

> #140
> requirements.txt 파일에 sqlalchemy 패키지 추가

[FEAT] SQLAlchemy 패키지를 requirements.txt에 추가 #140

---

backend/account/views.py

[STYLE] 회원가입 완료 문구 수정 #142

---

backend/account/management/commands/initadmin.py

> #146 
> initadmin.py 모듈에서 superuser의 is_active 옵션 True로 설정

[FIX] superuser 생성 시 활성화 상태로 수정 #146

---

backend/account/serializers.py

> #149 
> PasswordUpdateSerializer에서 비밀번호 변경 시 대소문자 구분하지 않도록 수정

[FIX] 비밀번호 변경 시 요구사항 수정 #149

---

.github/workflows/cd.yml
.github/workflows/ci.yml

> #151 
> CI 단계에서 테스트 실행 명령어 수정
> CI/CD 실행 조건 수정

[FIX] Github Actions 설정 수정 #151

---

backend/.pre-commit-config.yaml
backend/requirements.txt

> #156 
> pre-commit 설정에 types-pytz 추가
> requirements.txt에 types-pytz 제거

[FIX] pre-commit 설정 수정 #156

---

.github/workflows/ci.yml

> #158 
> ci.yml 스크립트에 DJANGO_SETTINGS_MODULE 설정 추가

[FIX] CI 스크립트에 설정 추가 #158

---

.github/workflows/ci.yml
backend/config/settings/base.py

> #160 
> CI 테스트용 데이터베이스 설정
> ci.yml 수정

[FIX] CI 테스트용 데이터베이스 설정 #160

---

.github/workflows/ci.yml
backend/config/settings/base.py
backend/config/settings/test.py

> #162 
> test.py에 테스트용 설정 작성
> ci.yml에 DJANGO_SETTINGS_MODULE 설정 수정

[CHORE] 테스트 설정 환경 분리 #162

---

backend/config/settings/base.py
backend/config/settings/dev.py
backend/config/settings/prod.py

[CHORE] 환경별로 로깅 설정 분리하기 #164

---

backend/pyproject.toml

> .
> pyproject.toml 설정에 pytest markers 설정 추가

[CHORE] pytest 설정 세팅

---

.gitignore
backend/.pre-commit-config.yaml
backend/account/schemas.py
backend/account/serializers.py
backend/account/views.py
backend/attendance/urls.py
backend/config/settings/base.py
backend/config/settings/dev.py
backend/config/urls.py
backend/config/utils.py
backend/mypage/schemas.py
backend/mypage/serializers.py
backend/mypage/views.py
backend/ranking/schemas.py
backend/ranking/serializers.py
backend/ranking/urls.py
backend/ranking/views.py
backend/record/schemas.py
backend/record/serializers.py
backend/record/views.py
backend/requirements.txt

> #167 
> 현재 운영 환경에서 사용 중인 기능에 대한 문서화

[DOCS] drf-spectacular를 사용한 Swagger documentation 작성 #167

---

.github/workflows/cd.yml

[CHORE] cd.yml 실행 조건 수정

---

nginx/nginx-app.conf

> .
> swagger ui 접속을 위한 Nginx 설정 수정

[CHORE] Nginx 설정 수정

---

backend/account/tests.py
backend/mypage/serializers.py
backend/mypage/tests.py
backend/tests/test_mypage/conftest.py
backend/tests/test_mypage/test_serializers.py

> #171
> mypage 앱의 모든 serializer 단위 테스트 작성

[TEST] mypage 앱 단위 테스트 작성 #171

---

backend/account/schemas.py
backend/requirements.txt
backend/tests/conftest.py
backend/tests/test_account/conftest.py
backend/tests/test_account/test_views.py
backend/tests/test_mypage/test_views.py

> #173 
> account 앱 통합 테스트 작성
> mypage 앱 통합 테스트 작성

[TEST] account, mypage 앱 통합 테스트 작성 #173

---

backend/attendance/services.py
backend/attendance/views.py

> #178 
> 출석률 조회 로직에 출석률 계산 로직 추가

[REFACTOR] 출석률 조회 기능 수정 #178

---

backend/attendance/views.py

> #180 
> 출석 거절 로직에 비관적 락 적용
> 출석 승인 로직의 통계 생성 부분 개선

[REFACTOR] 출석 거절 로직 비관적 락 적용 #180

---

backend/attendance/views.py

> #184 
> 출석 기간 관련 예외 처리 추가
> 대체 출석 횟수 필드 추가

[REFACTOR] 출석 내역 조회 로직 수정 #184

---

backend/attendance/serializers.py
backend/attendance/views.py

> #186 
> 운동 레벨을 문자로 반환하도록 수정
> 부원 목록 조회에 출석률 필드 추가

[REFACTOR] 부원 목록 조회 기능 수정 #186

---

backend/attendance/views.py

> #188 
> 금일 운동 지점 조회 기능 구현
> AttendanceViewSet 퍼미션을 각 메서드에서 지정하도록 변경

[FEAT] 금일 운동 지점 조회 기능 구현 #188

---

backend/account/views.py
backend/mypage/views.py
backend/ranking/views.py
backend/record/views.py

> #190 
> 로그인 시 토큰에 사용자 역할 정보 추가하도록 수정
> 불필요한 주석 제거

[FEAT] 토큰 생성 시 역할 정보 추가 #190

---

backend/record/serializers.py
backend/record/views.py

[REFACTOR] 운동 기록 관련 로직 수정 #196

---

.github/workflows/cd.yml
backend/attendance/views.py

> #200 
> 주말 및 공휴일일 때의 출석 요청에 대한 예외 처리 추가

[FIX] 주말 및 공휴일에 시도한 출석에 대한 처리 방식 수정 #200

---

backend/attendance/services.py
backend/attendance/tasks.py
backend/config/celery.py

> #202 
> 휴일날 출석 처리를 위한 테스크 생성
> 결석 처리를 위한 테스크 생성
> Celery Beat 스케줄러 설정

[FEAT] Celery Beat를 통한 결석 및 휴일 자동 처리 기능 구현 #202

---

backend/attendance/schemas.py
backend/attendance/views.py

> #204 
> 출석 관련 기능 Swagger documentation 설정

[DOCS] 출석 관련 기능 Swagger documentation 설정 #204

---

backend/ranking/services.py
backend/ranking/signals.py

[REFACTOR] 커스텀 예외 사용 및 pre-commit convention 적용

---

backend/mypage/serializers.py

> #213 
> 클래스 수준에서 workout_level 필드 선언 추가

[FIX] 마이페이지에서 운동 난이도 변경이 안되는 문제 해결 #213

---

backend/config/settings/prod.py

[CHORE] 운영 환경 데이터베이스 시간 설정 #219

---

backend/attendance/schemas.py
backend/attendance/urls.py
backend/attendance/views.py

[FEAT] 현재 기수 조회 구현 #221

---

backend/attendance/schemas.py
backend/attendance/urls.py
backend/attendance/views.py

> #223 
> 현재 기수 조회에서 최근 기수 조회로 수정

[REFACTOR] 현재 기수 조회 기능 수정 #223

---

backend/config/celery.py

[FIX] Celery beat 스케줄러가 동작하지 않는 문제 #225

---

docker-compose.prod.yml
redis.conf

[CHORE] Redis 설정 수정 #229

---

docker-compose.prod.yml
docker-compose.yml

[CHORE] Docker Compose 설정에서 Redis 서비스의 포트 매핑 제거 #231

---

backend/attendance/admin.py

> #234 
> admin에서 attendance에 request_processed_user가 None일 경우에 대한 처리 추가

[FIX] 자동으로 처리된 출석으로 인해 어드민의 출석 페이지 접속이 불가능한 문제 해결 #234

---

docker-compose.prod.yml
redis/redis.conf

[CHORE] Redis 메모리 설정 추가 #233
